server:
  port: 8080

spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

indexing:
  userAgent: "HeliontSearchBot"
  referrer: "http://www.google.com"
  minDelayMillis: 500
  maxDelayMillis: 5000
  sites:
    - url: "http://www.playback.ru/"
      name: "Playback"
#    - url: "https://volochek.life/"
#      name: "Volochek Life"

search:
  max-lemma-share: 0.7
  snippet-length: 200